apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

nodeGroups:
  - name: expense-spot
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    instancesDistribution:
      instanceTypes: ["m5.large", "c3.large", "c4.large", "c5.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 4
    spot: true

